// Package docsrouter builds docs/ROUTER.md: a standing index of every slug
// this workspace knows about, so a human can look up existing work by slug or
// topic instead of only by datetime path.
//
// It is not itself a dated deliverable under docs/<date>/<slug>/<version>/ -
// see AGENTS.md "Generated docs location", "never docs/<slug>/ for new work".
// A cross-cutting index scoped to no single slug is the documented exception,
// the same way .ai-agents/ROUTER.md is a router rather than a command output.
package docsrouter

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	state "github.com/ducnd58233/vibe-agent/runtime/internal/run"
	"github.com/ducnd58233/vibe-agent/runtime/internal/shared/runpath"
	"github.com/ducnd58233/vibe-agent/runtime/internal/shared/workspace"
)

const header = `# Docs router

Generated by ` + "`vibe-agent docs router`" + `. Do not hand-edit; regenerate instead.

| Slug | Version | Date | Title | Path |
|------|---------|------|-------|------|
`

// Generate returns the ROUTER.md content: one row per slug this workspace has
// a run-index or docs/.agent-state record for, sorted alphabetically by slug
// so a human scanning for a topic can find it without knowing the date.
//
// Deterministic: the same on-disk state always produces byte-identical
// output, so a no-op regeneration is not a diff.
func Generate(workspaceRoot string) (string, error) {
	slugs, err := runpath.ExistingSlugs(workspaceRoot)
	if err != nil {
		return "", err
	}
	sort.Strings(slugs)

	var b strings.Builder
	b.WriteString(header)
	for _, slug := range slugs {
		entry, err := runpath.Resolve(workspaceRoot, slug)
		if err != nil {
			continue // no run-index entry and nothing on disk; nothing to route to
		}
		relPath := filepath.ToSlash(filepath.Join(workspace.DocsDirName, entry.Date, slug, strconv.Itoa(entry.Version))) + "/"
		fmt.Fprintf(&b, "| %s | %d | %s | %s | `%s` |\n", slug, entry.Version, entry.Date, TitleFor(workspaceRoot, slug), relPath)
	}
	return b.String(), nil
}

// TitleFor is the one-line title for a slug's current revision: the SPEC's H1
// when one exists, else the manifest's own goal text. Used by both the
// ROUTER.md generator and `run list`'s title column so the two never drift.
func TitleFor(workspaceRoot, slug string) string {
	entry, err := runpath.Resolve(workspaceRoot, slug)
	if err != nil {
		return fallbackTitle(workspaceRoot, slug)
	}
	if title := specTitle(workspaceRoot, entry); title != "" {
		return title
	}
	return fallbackTitle(workspaceRoot, slug)
}

// specTitle reads the H1 line ("# Spec: ...") from the revision's SPEC file,
// or "" if no SPEC was written for this revision (a no-docs-* run, or older
// work from before that convention existed).
func specTitle(workspaceRoot string, entry runpath.Entry) string {
	basename, err := workspace.DocsArtifact("SPEC", entry.Date)
	if err != nil {
		return ""
	}
	dir := workspace.DocsDirAt(workspaceRoot, entry.Date, entry.Slug, entry.Version)
	if dir == "" {
		return ""
	}
	raw, err := os.ReadFile(filepath.Clean(filepath.Join(dir, basename)))
	if err != nil {
		return ""
	}
	for line := range strings.SplitSeq(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if after, ok := strings.CutPrefix(line, "# Spec:"); ok {
			return strings.TrimSpace(after)
		}
	}
	return ""
}

// fallbackTitle uses the manifest's own goal text when no SPEC exists for
// this slug - the case AGENTS.md's "no docs needed" convention documents.
func fallbackTitle(workspaceRoot, slug string) string {
	current, err := state.Load(state.ManifestPath(workspaceRoot, slug))
	if err != nil || current.Goal == "" {
		return "(no SPEC written for this slug)"
	}
	goal := current.Goal
	const max = 80
	if len(goal) > max {
		goal = goal[:max] + "..."
	}
	return goal + " (no SPEC written)"
}
