package sourcefiles

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ducnd58233/vibe-agent/runtime/internal/safexec"
)

func writeTree(t *testing.T, root string, files map[string]string) {
	t.Helper()
	for rel, content := range files {
		path := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}
}

func listed(t *testing.T, root string) string {
	t.Helper()
	files, err := List(t.Context(), root)
	if err != nil {
		t.Fatal(err)
	}
	var rels []string
	for _, f := range files {
		rels = append(rels, f.Rel)
	}
	return strings.Join(rels, ",")
}

// Dependencies, build output, caches, venvs under any name, and secrets are
// never the project's own source, whichever way the list is made.
var tree = map[string]string{
	"src/main.py":             "print(1)\n",
	"src/build.gradle.kts":    "plugins {}\n",
	"node_modules/x/index.js": "x\n",
	".venv/lib/a.py":          "x\n",
	"tools/env3/pyvenv.cfg":   "home = /usr\n",
	"tools/env3/lib/b.py":     "x\n",
	"build/gen.py":            "x\n",
	"target/A.class":          "x\n",
	"pkg/thing.egg-info/c.py": "x\n",
	"bazel-out/d.py":          "x\n",
	".env":                    "SECRET=1\n",
	"vendor/v.go":             "package v\n",
}

func TestTheWalkSkipsWhatIsNotTheProjectsOwnSource(t *testing.T) {
	root := t.TempDir()
	writeTree(t, root, tree)
	if got := listed(t, root); got != "src/build.gradle.kts,src/main.py" {
		t.Errorf("listed %s", got)
	}
}

func TestInsideGitTheListFollowsNestedIgnoreRules(t *testing.T) {
	if _, err := safexec.LookPath("git"); err != nil {
		t.Skip("git not installed")
	}
	root := t.TempDir()
	writeTree(t, root, tree)
	writeTree(t, root, map[string]string{
		"src/.gitignore":   "*.log\n!keep.log\n",
		"src/debug.log":    "x\n",
		"src/keep.log":     "x\n",
		"src/untracked.go": "package src\n",
	})
	cmd, err := safexec.CommandContext(t.Context(), "git", "init", "-q")
	if err != nil {
		t.Fatalf("git command: %v", err)
	}
	cmd.Dir = root
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git init: %v\n%s", err, out)
	}
	got := listed(t, root)
	want := "src/build.gradle.kts,src/keep.log,src/main.py,src/untracked.go"
	if got != want {
		t.Errorf("listed %s\nwant   %s", got, want)
	}
}

func TestReadableDropsBinaryGeneratedAndOversized(t *testing.T) {
	if Readable("a.bin", []byte{0, 1, 2, 0}) {
		t.Error("binary content is readable")
	}
	if Readable("x.pb.go", []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x\n")) {
		t.Error("generated content is readable")
	}
	if Readable("big.go", make([]byte, MaxFileBytes+1)) {
		t.Error("oversized content is readable")
	}
	if !Readable("a.go", []byte("package a\n")) {
		t.Error("ordinary source is not readable")
	}
}
