package harness

import (
	"fmt"
	"strings"
)

// The document is rendered from the table rather than written beside it.
//
// Five previous fixes to host wiring each edited documentation as well as code,
// and the documentation still drifted: d4c0b0c exists only to say what each
// host's hook surface "is now, not what it was". Two copies of one fact decay at
// different rates. One copy, plus a test that fails when the rendered form and
// the committed file disagree, is the arrangement that does not.

// HostContractsDoc is the path this renders to, relative to the toolkit root.
const HostContractsDoc = ".ai-agents/references/host-hook-contracts.md"

// RenderHostContracts produces the reference document.
func RenderHostContracts() string {
	var b strings.Builder

	b.WriteString("# Host hook contracts\n\n")
	b.WriteString("<context>\n\n")
	b.WriteString("**Generated from `runtime/internal/harness/contracts.go`. Do not edit this file by hand.**\n")
	b.WriteString("A test fails when the two disagree, and `doctor` reads the same table to check every\n")
	b.WriteString("host config in the workspace.\n\n")
	b.WriteString("This exists because the same class of defect was fixed five times without ever being\n")
	b.WriteString("written down: a wrong event key, a wrong output field, a host name the build could not\n")
	b.WriteString("answer, a failure half nobody recorded. Each fix added a check scoped to its own\n")
	b.WriteString("instance, so the next defect landed where no check looked. Documentation alone had\n")
	b.WriteString("already been tried; every one of those fixes edited docs too.\n\n")
	b.WriteString("Two rules govern this table:\n\n")
	b.WriteString("1. Every host carries a source URL. A claim the source does not support does not belong.\n")
	b.WriteString("2. **Verified** means someone watched a hook fire with that shape. A row taken from a\n")
	b.WriteString("   vendor page and never observed is `UNVERIFIED`, and says why. Writing wiring from\n")
	b.WriteString("   documentation and assuming it works is what produced the Cursor rows below.\n\n")
	b.WriteString("</context>\n")

	for _, host := range hostContracts {
		b.WriteString(renderHost(host))
	}
	return b.String()
}

// renderHost renders one host's section.
func renderHost(host HostContract) string {
	var b strings.Builder

	fmt.Fprintf(&b, "\n## %s\n\n<context>\n\n", host.Client)
	fmt.Fprintf(&b, "- **Config:** `%s`\n", host.ConfigPath)
	fmt.Fprintf(&b, "- **Source:** <%s>\n", host.Source)
	fmt.Fprintf(&b, "- **Workspace root:** %s\n", renderWorkspaceRoot(host.WorkspaceRoot))

	b.WriteString("\n| Host event key | vibe-agent event | Output keys the host reads | Inject | Refuse | Wired | Verified |\n")
	b.WriteString("|---|---|---|---|---|---|---|\n")
	for _, event := range host.Events {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s | %s |\n",
			event.HostKey,
			orNone(string(event.Event)),
			renderKeys(event.OutputKeys),
			yesNo(event.CanInject),
			yesNo(event.CanRefuse),
			yesNo(event.Wired),
			verifiedCell(event.Verification))
	}

	if notes := renderNotes(host); notes != "" {
		b.WriteByte('\n')
		b.WriteString(notes)
	}

	if reasons := renderReasons(host); reasons != "" {
		b.WriteByte('\n')
		b.WriteString(reasons)
	}

	if len(host.Gaps) > 0 {
		b.WriteString("\n**What this host does not provide**\n\n")
		for _, gap := range host.Gaps {
			fmt.Fprintf(&b, "- %s\n", gap)
		}
	}

	b.WriteString("\n</context>\n")
	return b.String()
}

// renderNotes collects the per-event prose.
//
// Below the table rather than inside it, because these run to several sentences
// and a table cell that long stops being readable as a table.
func renderNotes(host HostContract) string {
	var lines []string
	for _, event := range host.Events {
		if event.Note != "" {
			lines = append(lines, fmt.Sprintf("- `%s` - %s", event.HostKey, event.Note))
		}
	}
	if len(lines) == 0 {
		return ""
	}
	return "**Notes**\n\n" + strings.Join(lines, "\n") + "\n"
}

// renderReasons lists why the unverified rows are unverified, each distinct
// reason once.
//
// Once, because Cursor's eight rows share one reason and printing it eight
// times buries it. A reason repeated until it is skimmed past is the same as no
// reason, and this is the field the whole table turns on.
func renderReasons(host HostContract) string {
	var reasons []string
	byReason := map[string][]string{}
	for _, event := range host.Events {
		if event.Verified || event.Why == "" {
			continue
		}
		if _, seen := byReason[event.Why]; !seen {
			reasons = append(reasons, event.Why)
		}
		byReason[event.Why] = append(byReason[event.Why], "`"+event.HostKey+"`")
	}
	if len(reasons) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString("**Why the unverified rows are unverified**\n\n")
	for _, reason := range reasons {
		fmt.Fprintf(&b, "- %s\n  %s\n", strings.Join(byReason[reason], ", "), reason)
	}
	return b.String()
}

func renderWorkspaceRoot(root WorkspaceRoot) string {
	prefix := "**no reliable host variable.** "
	if root.Reliable {
		prefix = ""
		if root.Variable != "" {
			prefix = fmt.Sprintf("`%s`. ", root.Variable)
		}
	}
	return prefix + root.Note
}

func renderKeys(keys []string) string {
	if len(keys) == 0 {
		return "none"
	}
	quoted := make([]string, 0, len(keys))
	for _, key := range keys {
		quoted = append(quoted, "`"+key+"`")
	}
	return strings.Join(quoted, ", ")
}

func verifiedCell(v Verification) string {
	if v.Verified {
		return "yes"
	}
	return "**UNVERIFIED**"
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

func orNone(value string) string {
	if value == "" {
		return "-"
	}
	return "`" + value + "`"
}
